### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by SamBehm** [SamBehm/med-track#1]
# **Milestones**
 - [ ] Design a low-fidelity prototype of App UI 
 - [ ] Choose a cohesive and comprehensive colour scheme
 - [ ] Design assets to be used
 - [ ] Design high-fidelity prototype of App UI
 - [ ] Implementation of UI
